<?php
/**
 * Header
 *
 * @package #REPLACE-REPONAME
 * @author  Bright Bright Great <sayhello@brightbrightgreat.com>
 */

use bbg\wp\common\utility as u;
?><!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<meta content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">

		<!-- TODO: ICONS ARE GENERATED BY http://realfavicongenerator.net/ -->
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=jwLlGa2rny">
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=jwLlGa2rny">
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=jwLlGa2rny">
		<link rel="manifest" href="/manifest.json?v=jwLlGa2rny">
		<link rel="mask-icon" href="/safari-pinned-tab.svg?v=jwLlGa2rny" color="#ff205a">
		<link rel="shortcut icon" href="/favicon.ico?v=jwLlGa2rny">
		<meta name="theme-color" content="#ffffff">

		<?=wp_head()?>

	</head>

	<body <?=body_class()?>>

		<div id="vue-app" class="frame" v-cloak>
			<!-- ==============================================
				HEADER
			=============================================== -->
			<header class="s:header">

			</header>

			<main>
